// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using watchlist.Models;

namespace watchlist.Migrations
{
    [DbContext(typeof(MovieListContext))]
    [Migration("20190226031715_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("watchlist.Models.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("MovieListMLId");

                    b.Property<string>("MovieName")
                        .IsRequired()
                        .HasConversion(new ValueConverter<string, string>(v => default(string), v => default(string), new ConverterMappingHints(size: 64)))
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("MovieId");

                    b.HasIndex("MovieListMLId");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("watchlist.Models.MovieList", b =>
                {
                    b.Property<int>("MLId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("MovieListName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MLId");

                    b.ToTable("MovieLists");
                });

            modelBuilder.Entity("watchlist.Models.Movie", b =>
                {
                    b.HasOne("watchlist.Models.MovieList")
                        .WithMany("Movies")
                        .HasForeignKey("MovieListMLId");
                });
#pragma warning restore 612, 618
        }
    }
}
